# Welcome to Jekyll!

# Site variables -------
title: { desc::desc_get("Title") }
email: { system("git config user.email", intern = TRUE) }
description: { desc::desc_get("Description") }
baseurl: /{ desc::desc_get("Package") }
url: https://{ system('git config user.name', intern = TRUE) }.github.io/

# Package variables ----
package:
  name: { desc::desc_get("Package") }
  version: { desc::desc_get("Version") }
  url: { desc::desc_get("URL") }

# Build settings -------
collections_dir: collections
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Collections ----------
{ collections }

# Defaults -------------
{ defaults }

# Excluded files -------
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
